# Generated by Django 4.2 on 2023-04-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_productmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
    ]
