# Generated by Django 4.2 on 2023-04-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_productmodel_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invetory',
            new_name='Inventory',
        ),
    ]
