# Generated by Django 4.2 on 2023-04-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_rename_product_id_inbound_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], default='Free', max_length=1),
        ),
    ]
